name: provision destroy terraform
on: [workflow_dispatch]
jobs:
  provision:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@v4
       - name: terraform destroy
         run: terraform destroy -auto-approve
