- name: Download vaul repo file
  ansible.builtin.get.url:
   url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
   dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Vault
  ansible.builtin.dnf:
    name: vault
    state: latest

- name: start valult serivice
  ansible.builtin.systemd_service:
    name: vault
    state: restarted
    enabled: yes

